version: "3.9"
services:
  mysql:
    image: mysql:8.3
    container_name: remix-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: remix_sample
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mysql-volume:
